- name: Create k8s cluster
  hosts: localhost
  gather_facts: false

  roles:
    - role: nginx-ingress
      tags:
        - nginx-ingress
      when: nginx_ingress_enable

    - role: external-dns
      tags:
        - external-dns
      when: external_dns_enable

    - role: cert-manager
      tags:
        - cert-manager
      when: cert_manager_enable

    - role: hadoop
      tags:
        - hadoop
      when: hadoop_enable

    - role: jupyter
      tags:
        - jupyter
      when: binder_enable

    - role: minio
      tags:
        - minio
      when: minio_enable

    - role: keycloak
      tags:
        - keycloak
      when: keycloak_enable
