- name: Create k8s cluster
  hosts: localhost
  gather_facts: false
  environment:
    KUBECONFIG: "{{ kubeconfig }}"

  roles:
    - role: k8s-openstack
      when: k8s_enable_workarounds

    - role: external-dns
      tags:
        - external-dns
      when: external_dns_enable

    - role: cert-manager
      tags:
        - cert-manager
      when: cert_manager_enable

    - role: hadoop
      tags:
        - hadoop
      when: hadoop_enable

    - role: jupyter
      tags:
        - jupyter
      when: binder_enable
