- name: Dump OS k8s cluster data
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Gather network facts
      os_networks_facts:
        name: "demo"
      register: my_networks

    - name: Register network ids
      set_fact:
        network_ids: "{{ my_networks| json_query('ansible_facts.openstack_networks[*].id') }}"

    - set_fact: # cf. https://stackoverflow.com/a/37481293 for using sum to flatten an array of arrays
        subnet_ids: "{{ my_networks| json_query('ansible_facts.openstack_networks[*].subnets') | sum(start = []) }}"

    - name: Gather port facts
      os_port_facts:
      register: my_ports

    - name: Dump Network IDs
      debug:
        msg: "Network IDs: {{ network_ids  }}"

    - name: Dump Subnet IDs
      debug:
        msg: "Subnet IDs: {{ subnet_ids  }}"

    - name: Dump ports belonging to the nework
      debug:
        msg: "Port to delete: {{ item }}"
      when:
        - item.network_id in network_ids
        - item.name != ""
      loop: "{{ my_ports.ansible_facts.openstack_ports }}"

    - name: Delete loadbalancers
      os_loadbalancer:
        state: absent
        name: "{{ item.id }}"
        delete_public_ip: yes
      when:
        - item.network_id in network_ids
        - item.name | regex_search('(loadbalancer)')
      loop: "{{ my_ports.ansible_facts.openstack_ports }}"
      ignore_errors: True

    - name: Delete non-loadbalancer ports
      os_port:
        state: absent
        name: "{{ item.id }}"
        network: "{{ item.network_id }}"
      when:
        - item.network_id in network_ids
        - item.name == ""
      loop: "{{ my_ports.ansible_facts.openstack_ports }}"
      ignore_errors: True

    - name: Delete subnetworks
      os_subnet:
        state: absent
        name: "{{ item }}"
      loop: "{{ subnet_ids }}"
      ignore_errors: True
