- name: Workaround - Allow any TCP ingress traffic to nodes
  os_security_group_rule:
    security_group: "sg-{{ lookup('env','NAME') | default('k8s', true) }}-nodes"
    protocol: tcp

- name: Workaround - Allow any UDP ingress traffic to nodes
  os_security_group_rule:
    security_group: "sg-{{ lookup('env','NAME') | default('k8s', true) }}-nodes"
    protocol: udp

- name: Workaround - Allow any ICMP ingress traffic to nodes
  os_security_group_rule:
    security_group: "sg-{{ lookup('env','NAME') | default('k8s', true) }}-nodes"
    protocol: icmp
